const express = require('express')
const app = express()
const mongoose = require('mongoose')
const cors = require('cors')
const appController = require('../backend/Controllers/appController')
const empController = require('../backend/Controllers/empController')
const skillController = require('../backend/Controllers/skillController')
const servController = require('../backend/Controllers/servController')
require('dotenv').config()

mongoose.connect(process.env.MONGO_URL)
.then(() => console.log("MongoDB is Connected"))
.catch(error => {
    console.log("Connection Failed")
    console.log(error)
})

app.use(express.json())
app.use(cors())
app.post("/registerA", appController.registerA)
app.post("/loginA", appController.loginA)
app.post("/editApplicant", appController.editApplicant)
app.post("/deleteApplicant", appController.deleteApplicant)
app.post("/registerE", empController.registerE)
app.post("/loginE", empController.loginE)
app.post("/editEmployer", empController.editEmployer)
app.post("/deleteEmployer", empController.deleteEmployer)
app.post("/displayEmployers", empController.displayEmployers)
app.post("/createSkill/:email", skillController.createSkill)
app.post("/editSkill", skillController.editSkill)
app.post("/deleteSkill", skillController.deleteSkill)
app.post("/createService", servController.createService)
app.post("/editService", servController.editService)
app.post("/deleteService", servController.deleteService)
app.listen(9000, () => console.log("Port 9000 is Active"))